language: java

jdk: oraclejdk8

env:
  global:
    - JVM_OPTS="-XX:MaxPermSize=256m -Xmx1024m"

notifications:
  email:
    recipients:
      - github@crossing-tech.com
    on_success: never  #default: change
    on_failure: always #default: always
  irc: "irc.codehaus.org#babel"
